### ISSUE TITLE
Documentation and/or examples using known estimates in PyQIR

### ISSUE THREAD

**Issue by skushnir123** [qir-alliance/pyqir#268]
**Is your feature request related to a problem? Please describe.**
Q* allows quantum programs to specify known estimates used in the Microsoft Resource Estimator. Given that QIR is a valid input to the Microsoft Resource Estimator, I would expect there to be similar functionality provided in QIR through PyQIR. 

If this already exists, I think it would be helpful to have more documentation/examples surrounding this. If it doesn't, then I think this would be a vital addition to PyQIR.

**Comment by idavis** [comment]
Hi @skushnir123, PyQIR is primarily designed for hardware targeted QIR. It can parse arbitrary QIR produced with LLVM14 and older, but generation is limited as it focuses on profile compliant code generation rather than unrestricted LLVM IR/BC.

For resource estimation I'd recommend calculating your code's logical count and leveraging the [qsharp](https://pypi.org/project/qsharp/) Python package's resource estimation ([announcement](https://devblogs.microsoft.com/qsharp/design-fault-tolerant-quantum-computing-applications-with-the-open-source-resource-estimator/), [space-time tradeoffs](https://devblogs.microsoft.com/qsharp/exploring-space-time-tradeoffs-with-azure-quantum-resource-estimator/)) APIs.
